#!/usr/bin/env bash

readonly DEFAULT_MON="eDP1"
MONITORS=()

mapfile -t MONITORS < <(xrandr | grep -P -e "\bconnected\b" | cut -d' ' -f1)
readonly MONITORS

IFS=$'\n'


for mon in "${MONITORS[@]}"; do
    if [ "$mon" = "$DEFAULT_MON" ]; then
        continue
    fi

    echo "Trying to fix output $mon..."
    xrandr --output "$mon" --mode 1920x1080 --above eDP1 --primary -v -d :0
    res="$?"

    if [ "$res" -eq 0 ]; then
        echo "Succesfully fixed output $mon"
        echo "Restarting polybar.service"
        systemctl --user restart polybar.service
        exit 0
    else
        echo "Failed to fix output for $mon"
        exit 1
    fi
done

