#!/usr/bin/env bash

echo "Killing polybar"
PID=$(pgrep -f "polybar --reload main" | grep -v $$)
kill $PID

echo "Starting polybar"
rm -rf /tmp/polybar_mqueue.*
for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar --reload main &
done

echo "Done"
